import AuthSession from 'app/components/common/auth/AuthSession';
import './globals.css';

export const metadata = {
  title: 'quokka letter',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <AuthSession>
        <body>
          <div>hi</div>
          {children}
        </body>
      </AuthSession>
    </html>
  );
}
